import { Color } from '../models/Color';

const holidays = [{
  "_date": "2018-10-03",
  "_note": "개천절",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "true",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-09",
  "_note": "한글날",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "true",
  "_isHoliday": "true",
},{
  "_date": "2018-10-20",
  "_note": "단잡설명회",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-22",
  "_note": "여권사진촬영",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-23",
  "_note": "필라테스등록",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-26",
  "_note": "여권만들기",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-27",
  "_note": "은혜님청첩장",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
},{
  "_date": "2018-10-28",
  "_note": "통기타",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-30",
  "_note": "수영 마지막",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-31",
  "_note": "실업인정일",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-31",
  "_note": "여권찾기",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-31",
  "_note": "영화",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-10-31",
  "_note": "실업급여기업은행",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-01",
  "_note": "병원",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-02",
  "_note": "필라테스시작",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-02",
  "_note": "강민호",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-03",
  "_note": "언니랑영화",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-04",
  "_note": "통기타",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-11-10",
  "_note": "GDG DevFest seoul 2018",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
},{
  "_date": "2018-11-13",
  "_note": "Superb AI 2차 면접",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2019-04-01",
  "_note": "미국비자발급",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2019-10-01",
  "_note": "미국일할수있는 날짜",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-12-10",
  "_note": "첫출근",
  "_detail": "뉴럴비씨 첫출근",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-12-15",
  "_note": "결혼식",
  "_detail": "은혜님 결혼식",
  "_color": new Color(),
  "_isRepeat": "false",
  "_isHoliday": "true",
}, {
  "_date": "2018-01-02",
  "_note": "신정",
  "_detail": "",
  "_color": new Color(),
  "_isRepeat": "true",
  "_isHoliday": "true",
}];

export class HolidayService {

  getHolidays() {
    return holidays;
  }
}
